### ISSUE TITLE
SRI violation reporting

### ISSUE THREAD

**Issue by xtuc** [w3c/network-error-logging#155]
It would be useful to report [SRI](https://www.w3.org/TR/SRI/) violation in NEL.

With [cdnjs.com](https://cdnjs.com/) we recommend people to install their script with the SRI attribute with the hash we calculated in our pipeline.
Sometimes it happens (by mistake) that files change on cdnjs, the SRI might change and, if not equal to the previous SRI, break people's installation.

Currently, as far as I'm aware, there's no good way to tell if cdnjs users are seeing SRIs violation.

More generally, I think this would benefit other use cases. Related example https://blog.cloudflare.com/cloudflare-verifies-code-whatsapp-web-serves-users/ to some extend.

**Comment by clelland** [comment]
I certainly see the usefulness of reporting these violations; I'm not convinced, though, that NEL is the right place, as they're not really network-layer errors. They feel more akin to CSP violations, which would be configured separately (and per-document, not per-origin like NEL)

**Comment by clelland** [comment]
Discussed at TPAC, and the sentiment was that this is definitely something that should be reported, but that NEL specifically probably isn't the right mechanism. I think it would be worth opening an issue on [SRI](https://github.com/w3c/webappsec-subresource-integrity) to integrate with the Reporting API; I suspect that the document reporting model should suffice for this, since it deals with subresources.
