### ISSUE TITLE
uri -> url

### ISSUE THREAD

**Issue by annevk** [w3c/network-error-logging#47]
This is what we call URLs pretty much everywhere.

**Comment by igrigorik** [comment]
FWIW, I've considered switching `report-uri` to `report-url` but opted against it to be consistent with CSP: http://www.w3.org/TR/CSP2/#directive-report-uri ... perhaps not ideal, but it seems like the kind of quirk that would drive people nuts if they were different. /cc @mikewest

Closing, but if you feel otherwise, feel free to reopen :)

**Comment by annevk** [comment]
I'm not a fan, but I guess CSP did set a precedent for this :-(
