### ISSUE TITLE
Other 4xx server responses when submitting errors

### ISSUE THREAD

**Issue by bagder** [w3c/network-error-logging#60]
The spec spells out that when getting a 410 back from a server when submitting an error, the `report-uri` MUST be removed from the list of URIs to submit to.

I'm concerned of the case when a bad actor manages to insert NEL: headers in N origins, all pointing out `report-uris` on a victim's host (making it a sort of DDOS attack). Such a `report-uri` of an unwilling receiver is unlikely to ever return a 410 to stop further reports, but are more likely to respond with a 2xx as long as it works, or perhaps more likely a 4xx.

I propose any 4xx error on submission should be reason for removal.

**Comment by igrigorik** [comment]
> The spec spells out that when getting a 410 back from a server when submitting an error, the report-uri MUST be removed from the list of URIs to submit to.

We restrict NEL registration to HTTPS origins only. If someone is MITM'ing you.. you probably have a bigger problem?

**Comment by bagder** [comment]
I was thinking of cases where an attacker manages to for example insert scripts in a PHP setup or similar (ie not fully "owned", just tricked into delivering data inserted from the outside). The site would still be HTTPS and sent from the original site.

The difference with for example inserting an image tag in the HTML (or similar), is the amplification effect since a NEL-supporting browser would keep sending HTTP POST to the report-uri site for 24 hours or so (albeit slower and slower).

Lastly, I don't see a reason to think of other 4xx responses as transient. The POST is clearly failing and it is a "client error" according to the server (ie that's what 4xx errors mean) so I think a client should be discouraged to try the same POST again to the same URI for that NEL-origin.

**Comment by bagder** [comment]
A related issue: while visiting site A it sends NEL: headers with one of the `report-uri` fields pointing to site B that is returning 410. If site A keeps sending the same NEL header set during the users stay (which seems likely for a certain set of servers), a client will almost immediately add the bad report-uri back into its NEL policy again for that origin and it will lead to more POSTs to B in spite of it sending 410...

**Comment by igrigorik** [comment]
I'm not sure the attack is practical.. First you have to compromise an HTTPS server and inject the NEL registration, then you'd have to make the client visit it once to pick up the registration, break/take down the HTTPS server and then trick the client into opening the same URL one or multiple times to trigger report delivery... Seems like there are much simpler ways to generate traffic to a report-uri?

Now, that said, yes we could treat all 4xx's as signal to remove registration. Would this extend to all 500's? If so, then effectively we're saying that any non 2xx response is a signal to remove registration. This may be reasonable.. the origin can just reinstate the registration later if something went wrong and the 4xx/5xx was a transient error.

Re, re-registering the same report-uri's: don't think there is any clever way to work around this in light of above? The UA could keep some history and blacklist hosts that trigger such registrations, etc? That is, don't block the report-uri's but block the origin that's registering report-uri's that then return 4xx/5xx?

**Comment by dcreager** [comment]
This issue is quite old, so I'm going to close it:

- The spec currently gives user agents leeway in how aggressive to be in backing off of failed uploads, and I think this flexibility is the correct approach.  We don't have to mandate something more aggressive — although user agents are free to implement something aggressive should they choose.  410 is a clear signal from the collector that they want to take themselves out of contention.

- If the worry is about causing user agents to DDOS a collector, there are enough extra steps involved that NEL isn't adding new attack capabilities.  As @igrigorik mentioned, at the end of the day, you have to get the user agent to make at least one request to your NEL origin for each request that you want it to make to the collector that you're targeting with the DDOS.  If you can get the user agent to make all of those requests to your NEL origin, you might as well just have them make the requests directly to the collector.  (I.e., NEL doesn't allow any amplification attacks)

- Moreover, with report batching, there's a limit to how frequently the user agent will make *any* requests to the collectors.  Chrome's implementation, for instance, only uploads reports once per minute, regardless of how many NEL origin requests have been made during that minute.

- Lastly, report uploads are now covered by CORS, so the user agent will need to make a preflight request before uploading any reports.  That won't contain any of the report payload (less bandwidth / processing load per request on the collector), and the server has a chance to reject upload requests from (well-behaved) user agents.
